### PR TITLE
chore: Update README with new install instructions.

### PR DESCRIPTION
**Pull request by drhayes**

### CODE REVIEW

**Review by mikemartin1090 — DISMISSED** [review]
I see how this works. Be sure you have your .npmrc setup!

image

**Comment by mikemartin1090** [comment]
In the same vein of updating the readme, does this line need to change now? From `require('node-logger');` to `require('@glg/node-logger');` ??

**Comment by drhayes** [comment]
Oh, that is a *super* good catch. Updated.

**Review by mikemartin1090 — APPROVED** [review]
Acceptable to me!

**Pull request merged**
